# Generated by Django 5.2.17 on 2026-08-31 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('PRODUCT', 'Product session'), ('SHOW', 'Show session')], default='PRODUCT', max_length=8)),
                ('session_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('confirmed_count', models.PositiveIntegerField(default=0)),
                ('held_count', models.PositiveIntegerField(default=0)),
                ('booking_cutoff_minutes', models.PositiveIntegerField(default=0)),
                ('grace_minutes', models.PositiveSmallIntegerField(default=0)),
                ('reservation_mode', models.CharField(choices=[('NONE', 'No reservation required'), ('OPTIONAL', 'Reservation optional'), ('REQUIRED', 'Reservation required')], default='REQUIRED', max_length=10)),
                ('check_in_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('AVAILABLE', 'Available'), ('LIMITED', 'Limited availability'), ('FULL', 'Full'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('HIDDEN', 'Hidden')], default='SCHEDULED', max_length=12)),
                ('publication_state', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('customer_visible', models.BooleanField(default=True)),
                ('delayed_start_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('origin', models.CharField(choices=[('ONE_OFF', 'One-off addition'), ('PATTERN', 'From a recurring pattern'), ('OVERRIDE', 'Date-specific override')], default='ONE_OFF', max_length=12)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='tenancy.area')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='catalog.experience')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='tenancy.venue')),
            ],
            options={
                'ordering': ['session_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_ref', models.CharField(db_index=True, max_length=40)),
                ('channel', models.CharField(default='ONLINE', max_length=12)),
                ('quantity', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('HELD', 'Held'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('RELEASED', 'Released')], default='HELD', max_length=10)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='inventory.session')),
            ],
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['venue', 'session_date', 'kind'], name='inventory_s_venue_i_f747da_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['product', 'session_date'], name='inventory_s_product_bcb4fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('confirmed_count__lte', models.F('capacity')), _connector='OR'), name='confirmed_never_exceeds_capacity'),
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(fields=['session', 'state'], name='inventory_h_session_8c648d_idx'),
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(fields=['state', 'expires_at'], name='inventory_h_state_c7a844_idx'),
        ),
    ]
