# Generated by Django 5.2.17 on 2026-08-31 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(db_index=True, max_length=40)),
                ('state', models.CharField(choices=[('ISSUED', 'Issued'), ('VALID', 'Valid'), ('USED', 'Used'), ('PARTIALLY_USED', 'Partially used'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('VOIDED', 'Voided'), ('REFUNDED', 'Refunded'), ('TRANSFERRED', 'Transferred'), ('BLOCKED', 'Blocked')], db_index=True, default='VALID', max_length=16)),
                ('visit_date', models.DateField(db_index=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(db_index=True)),
                ('validity_timezone', models.CharField(max_length=64)),
                ('validity_type', models.CharField(default='END_OF_VISIT_DAY', max_length=20)),
                ('validity_policy', models.JSONField(blank=True, default=dict)),
                ('entry_allowance', models.PositiveSmallIntegerField(default=1, help_text='0 means unlimited.')),
                ('entries_used', models.PositiveSmallIntegerField(default=0)),
                ('reentry_allowed', models.BooleanField(default=False)),
                ('reentry_window_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('first_entry_at', models.DateTimeField(blank=True, null=True)),
                ('last_entry_at', models.DateTimeField(blank=True, null=True)),
                ('proof_required', models.BooleanField(default=False)),
                ('blocked_reason', models.CharField(blank=True, max_length=200)),
                ('qr_payload', models.CharField(max_length=255, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('reissue_count', models.PositiveSmallIntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='booking.booking')),
                ('booking_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='booking.bookingitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.customersegment')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='inventory.session')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.tickettype')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tenancy.venue')),
            ],
            options={
                'ordering': ['ticket_number'],
                'indexes': [models.Index(fields=['tenant', 'state', 'visit_date'], name='ticketing_t_tenant__29a159_idx'), models.Index(fields=['venue', 'visit_date'], name='ticketing_t_venue_i_60fde8_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'ticket_number'), name='uniq_ticket_number_per_tenant'), models.CheckConstraint(condition=models.Q(('entry_allowance', 0), ('entries_used__lte', models.F('entry_allowance')), _connector='OR'), name='entries_never_exceed_allowance')],
            },
        ),
    ]
