services:
  - type: web
    name: aquaria-api
    runtime: python
    plan: free
    region: singapore
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    preDeployCommand: python manage.py migrate --noinput
    initialDeployHook: python seed.py
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /api/health/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        fromService:
          name: aquaria-api
          type: web
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: TICKET_SIGNING_KEY
        generateValue: true
      - key: USE_SQLITE_FALLBACK
        value: "0"
