# Generated by Django 5.2.17 on 2026-08-31 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(default='THB', max_length=3)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_until', models.DateField(blank=True, null=True)),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='Empty means every weekday.')),
                ('channel', models.CharField(blank=True, help_text='Blank means any channel.', max_length=12)),
                ('quantity_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quantity_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher wins. Ties break on scope specificity.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=12)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='inventory.session')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_rules', to='catalog.tickettype')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_rules', to='tenancy.venue')),
            ],
            options={
                'ordering': ['-priority', '-date_from'],
                'indexes': [models.Index(fields=['ticket_type', 'status', 'priority'], name='pricing_pri_ticket__7d6cc1_idx'), models.Index(fields=['venue', 'status'], name='pricing_pri_venue_i_465a7d_idx')],
            },
        ),
    ]
