# Generated by Django 5.2.17 on 2026-08-31 05:27

import apps.tenancy.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.JSONField(default=dict)),
                ('description', models.JSONField(blank=True, default=dict)),
                ('image_url', models.URLField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('floor', models.CharField(blank=True, max_length=30)),
                ('map_ref', models.CharField(blank=True, max_length=120)),
                ('directions', models.JSONField(blank=True, default=dict)),
                ('display_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tenancy.area')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.JSONField(default=dict)),
                ('direction', models.CharField(choices=[('IN', 'Entry'), ('OUT', 'Exit'), ('BOTH', 'Both')], default='IN', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_points', to='tenancy.area')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='tenancy.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.JSONField(default=dict, help_text='Translatable: {"en": "Aquaria Phuket", "th": "..."}')),
                ('short_name', models.CharField(blank=True, max_length=60)),
                ('venue_type', models.CharField(default='GENERIC', max_length=40)),
                ('timezone', models.CharField(default='Asia/Bangkok', max_length=64, validators=[apps.tenancy.models.validate_iana_timezone])),
                ('currency', models.CharField(default='THB', max_length=3)),
                ('tax_model', models.CharField(choices=[('INCLUSIVE', 'Tax included in the displayed price'), ('EXCLUSIVE', 'Tax added to the displayed price')], default='INCLUSIVE', max_length=10)),
                ('tax_rate_bp', models.PositiveIntegerField(default=0, help_text='Basis points. Thai VAT of 7% is 700.')),
                ('rounding_mode', models.CharField(choices=[('NONE', 'No rounding'), ('NEAREST_1', 'Nearest 1'), ('NEAREST_5', 'Nearest 5'), ('NEAREST_10', 'Nearest 10'), ('UP_1', 'Always up to 1'), ('DOWN_1', 'Always down to 1')], default='NONE', max_length=12)),
                ('address', models.TextField(blank=True)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('logo_url', models.URLField(blank=True)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('customer_visible', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='tenancy.brand')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='tenancy.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('KIOSK', 'Self-service kiosk'), ('POS', 'Counter POS'), ('SCANNER', 'Gate scanner'), ('PRINTER', 'Printer')], max_length=16)),
                ('channel', models.CharField(default='ONLINE', max_length=12)),
                ('credential_hash', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('access_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='tenancy.accesspoint')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='tenancy.venue')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='tenancy.venue'),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_points', to='tenancy.venue'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_org_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_brand_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_venue_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_device_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('venue', 'code'), name='uniq_area_code_per_venue'),
        ),
        migrations.AddConstraint(
            model_name='accesspoint',
            constraint=models.UniqueConstraint(fields=('venue', 'code'), name='uniq_access_point_code_per_venue'),
        ),
    ]
