# Generated by Django 5.2.17 on 2026-08-31 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_role', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=60)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('channel', models.CharField(blank=True, max_length=20)),
                ('device', models.CharField(blank=True, max_length=40)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('occurred_at_utc', models.DateTimeField(db_index=True)),
                ('occurred_at_local', models.CharField(blank=True, max_length=40)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.venue')),
            ],
            options={
                'ordering': ['-occurred_at_utc'],
                'indexes': [models.Index(fields=['tenant', 'action', 'occurred_at_utc'], name='core_audite_tenant__ac3275_idx'), models.Index(fields=['tenant', 'target_type', 'target_id'], name='core_audite_tenant__8727d2_idx')],
            },
        ),
    ]
