# Generated by Django 5.2.17 on 2026-08-31 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.JSONField(default=dict, help_text='Translatable, e.g. {"en": "Adult"}')),
                ('description', models.JSONField(blank=True, default=dict)),
                ('display_order', models.IntegerField(default=0)),
                ('qualification', models.JSONField(blank=True, default=dict)),
                ('proof_required_at_entry', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SCHEDULED', 'Scheduled for future availability'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60)),
                ('kind', models.CharField(choices=[('ADMISSION', 'Admission'), ('SHOW', 'Show or performance'), ('CLASS', 'Class or workshop'), ('TOUR', 'Guided tour'), ('RESOURCE', 'Bookable resource'), ('EVENT', 'Special event')], default='ADMISSION', max_length=12)),
                ('name', models.JSONField(default=dict)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('description', models.JSONField(blank=True, default=dict)),
                ('customer_instructions', models.JSONField(blank=True, default=dict)),
                ('cancellation_message', models.JSONField(blank=True, default=dict)),
                ('cover_image_url', models.URLField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(blank=True, db_index=True, max_length=60)),
                ('default_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('recommended_audience', models.CharField(blank=True, max_length=120)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('display_priority', models.IntegerField(default=0)),
                ('customer_visible', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SCHEDULED', 'Scheduled for future availability'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to='tenancy.area')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to='tenancy.venue')),
            ],
            options={
                'ordering': ['display_priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60)),
                ('name', models.JSONField(default=dict)),
                ('description', models.JSONField(blank=True, default=dict)),
                ('admission_model', models.CharField(default='GENERAL_ADMISSION', help_text='Configurable archetype, e.g. GENERAL_ADMISSION, TIMED_ENTRY, DAY_PASS (R3.1).', max_length=30)),
                ('session_requirement', models.CharField(choices=[('NOT_USED', 'Sessions not used'), ('OPTIONAL', 'Session optional'), ('REQUIRED', 'Session required')], default='NOT_USED', max_length=10)),
                ('seat_requirement', models.CharField(choices=[('NOT_USED', 'No seat assignment'), ('OPTIONAL', 'Seat optional'), ('REQUIRED', 'Seat required')], default='NOT_USED', max_length=10)),
                ('channels', models.JSONField(blank=True, default=list, help_text='Empty means every channel.')),
                ('min_per_booking', models.PositiveSmallIntegerField(default=1)),
                ('max_per_booking', models.PositiveSmallIntegerField(default=10)),
                ('display_order', models.IntegerField(default=0)),
                ('customer_visible', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SCHEDULED', 'Scheduled for future availability'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.experience')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='tenancy.venue')),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(choices=[('BUNDLE_ITEM', 'Bundle item'), ('ADDON', 'Add-on')], max_length=12)),
                ('min_quantity', models.PositiveSmallIntegerField(default=0)),
                ('max_quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_relations', to='catalog.product')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60)),
                ('name', models.JSONField(default=dict)),
                ('description', models.JSONField(blank=True, default=dict)),
                ('admission_model', models.CharField(blank=True, max_length=30)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('min_quantity', models.PositiveSmallIntegerField(default=0)),
                ('max_quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('entry_allowance', models.PositiveSmallIntegerField(default=1, help_text='0 means unlimited entries.')),
                ('reentry_allowed', models.BooleanField(default=False)),
                ('eligibility', models.JSONField(blank=True, default=dict)),
                ('transferable', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('customer_visible', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SCHEDULED', 'Scheduled for future availability'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_types', to='catalog.product')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_types', to='catalog.customersegment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='customersegment',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_segment_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.UniqueConstraint(fields=('venue', 'code'), name='uniq_experience_code_per_venue'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('venue', 'code'), name='uniq_product_code_per_venue'),
        ),
        migrations.AddConstraint(
            model_name='productrelation',
            constraint=models.UniqueConstraint(fields=('parent', 'child', 'relation'), name='uniq_product_relation'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_ticket_type_code_per_tenant'),
        ),
    ]
