# Generated by Django 5.2.17 on 2026-08-31 05:27

import apps.tenancy.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketValidityPolicy',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validity_type', models.CharField(choices=[('END_OF_VISIT_DAY', 'End of visit day (23:59:59 venue local)'), ('NUMBER_OF_DAYS', 'A number of days'), ('FIXED_DURATION', 'A fixed duration in minutes'), ('FIXED_RANGE', 'A fixed date/time range'), ('SESSION_BASED', 'Bound to a session'), ('MEMBERSHIP_BASED', 'Follows membership rights'), ('CUSTOM', 'Custom access rule')], default='END_OF_VISIT_DAY', max_length=20)),
                ('number_of_days', models.PositiveSmallIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_start_time', models.TimeField(blank=True, null=True)),
                ('entry_cutoff_time', models.TimeField(blank=True, null=True)),
                ('grace_minutes', models.PositiveSmallIntegerField(default=0)),
                ('reentry_allowed', models.BooleanField(default=False)),
                ('reentry_window_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('max_entries', models.PositiveSmallIntegerField(default=1, help_text='0 means unlimited entries.')),
                ('effective_from', models.DateField(db_index=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validity_policies', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validity_policies', to='tenancy.venue')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='VenueTimezoneChange',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_timezone', models.CharField(max_length=64, validators=[apps.tenancy.models.validate_iana_timezone])),
                ('new_timezone', models.CharField(max_length=64, validators=[apps.tenancy.models.validate_iana_timezone])),
                ('reason', models.TextField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timezone_changes', to='tenancy.venue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Units of to_currency per one from_currency.', max_digits=20)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=12)),
                ('source', models.CharField(default='MANUAL', max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates', to='tenancy.venue')),
            ],
            options={
                'ordering': ['-effective_from'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('venue', 'from_currency', 'to_currency', 'effective_from'), name='uniq_active_rate_per_pair_and_date')],
            },
        ),
        migrations.CreateModel(
            name='ServiceChargeSetting',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('rate_bp', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000)])),
                ('mode', models.CharField(choices=[('INCLUSIVE', 'Included in the displayed price'), ('EXCLUSIVE', 'Added at checkout')], default='EXCLUSIVE', max_length=10)),
                ('display_name', models.CharField(default='Service charge', max_length=60)),
                ('effective_from', models.DateField(db_index=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_charge_settings', to='tenancy.venue')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['venue', 'effective_from'], name='venuesettin_venue_i_5bd3f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportedCurrency',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='ISO 4217, e.g. THB.', max_length=3)),
                ('is_base', models.BooleanField(default=False)),
                ('display_enabled', models.BooleanField(default=True)),
                ('payment_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currencies', to='tenancy.venue')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('venue', 'code'), name='uniq_currency_per_venue'), models.UniqueConstraint(condition=models.Q(('is_base', True)), fields=('venue',), name='uniq_base_currency_per_venue')],
            },
        ),
        migrations.CreateModel(
            name='VatSetting',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('rate_bp', models.PositiveIntegerField(default=700, help_text='Basis points. 7% VAT is 700. Max 10000 (100%).', validators=[django.core.validators.MaxValueValidator(10000)])),
                ('mode', models.CharField(choices=[('INCLUSIVE', 'Included in the displayed price'), ('EXCLUSIVE', 'Added at checkout')], default='INCLUSIVE', max_length=10)),
                ('display_name', models.CharField(default='VAT', max_length=60)),
                ('tax_registration', models.CharField(blank=True, max_length=60)),
                ('effective_from', models.DateField(db_index=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vat_settings', to='tenancy.venue')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['venue', 'effective_from'], name='venuesettin_venue_i_f5cf1f_idx')],
            },
        ),
    ]
