"""A08 Software and Data Integrity: upload validation.

Photos (venue logos, area images, show covers, seat-map backgrounds) are uploaded to
S3. The declared ``Content-Type`` and the filename are both attacker-controlled, so
neither is trusted:

* the **magic bytes** decide the type, not the extension;
* SVG is rejected outright, because an SVG is a script-execution vector and no
  requirement needs it;
* the stored object key is generated by the platform, never derived from the
  submitted filename, which removes path traversal and overwrite attacks entirely;
* every object is stored with ``Content-Disposition: attachment`` and a pinned
  ``Content-Type``, so a file that slips through cannot be rendered as HTML from the
  media origin.

Validation happens twice: :func:`validate_upload_request` before a presigned URL is
issued, and :func:`validate_bytes` when the upload is finalized. The first bounds what
can be requested; the second is what actually inspects content, because the browser
uploads straight to S3 without passing through the application.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from typing import Iterable

from ..core.errors import ValidationError
from ..core.ids import new_id

#: Permitted image types, each pinned to its magic-byte signature(s).
IMAGE_SIGNATURES: dict[str, tuple[bytes, ...]] = {
    "image/jpeg": (b"\xff\xd8\xff",),
    "image/png": (b"\x89PNG\r\n\x1a\n",),
    "image/gif": (b"GIF87a", b"GIF89a"),
    "image/webp": (b"RIFF",),  # plus a 'WEBP' check at offset 8
    "application/pdf": (b"%PDF-",),
}

#: Types accepted for customer-visible media.
ALLOWED_IMAGE_TYPES: frozenset[str] = frozenset({"image/jpeg", "image/png", "image/gif", "image/webp"})

#: Types accepted for generated financial documents.
ALLOWED_DOCUMENT_TYPES: frozenset[str] = frozenset({"application/pdf"})

#: Never accepted. SVG and HTML execute script; the rest are executable payloads.
FORBIDDEN_TYPES: frozenset[str] = frozenset(
    {
        "image/svg+xml",
        "text/html",
        "application/xhtml+xml",
        "text/xml",
        "application/xml",
        "application/javascript",
        "text/javascript",
        "application/x-msdownload",
        "application/x-sh",
        "application/x-httpd-php",
        "application/octet-stream",
    }
)

EXTENSION_BY_TYPE: dict[str, str] = {
    "image/jpeg": "jpg",
    "image/png": "png",
    "image/gif": "gif",
    "image/webp": "webp",
    "application/pdf": "pdf",
}

MAX_IMAGE_BYTES = 10 * 1024 * 1024
MAX_DOCUMENT_BYTES = 20 * 1024 * 1024
MIN_BYTES = 64

#: Kinds of media the platform stores, each with its own limits.
MEDIA_KINDS: dict[str, dict[str, object]] = {
    "VENUE_LOGO": {"types": ALLOWED_IMAGE_TYPES, "max_bytes": 2 * 1024 * 1024},
    "AREA_IMAGE": {"types": ALLOWED_IMAGE_TYPES, "max_bytes": MAX_IMAGE_BYTES},
    "SHOW_COVER": {"types": ALLOWED_IMAGE_TYPES, "max_bytes": MAX_IMAGE_BYTES},
    "SHOW_GALLERY": {"types": ALLOWED_IMAGE_TYPES, "max_bytes": MAX_IMAGE_BYTES},
    "SEAT_MAP_BACKGROUND": {"types": ALLOWED_IMAGE_TYPES, "max_bytes": MAX_IMAGE_BYTES},
    "SEAT_VIEW_IMAGE": {"types": ALLOWED_IMAGE_TYPES, "max_bytes": MAX_IMAGE_BYTES},
    "PRODUCT_IMAGE": {"types": ALLOWED_IMAGE_TYPES, "max_bytes": MAX_IMAGE_BYTES},
    "TAX_DOCUMENT": {"types": ALLOWED_DOCUMENT_TYPES, "max_bytes": MAX_DOCUMENT_BYTES},
}

_SAFE_KEY = re.compile(r"^[a-z0-9][a-z0-9/_.-]{0,255}$")


@dataclass(frozen=True, slots=True)
class UploadPlan:
    """A validated upload request, ready to be turned into a presigned PUT."""

    asset_id: str
    kind: str
    object_key: str
    content_type: str
    max_bytes: int
    #: Headers the presigned URL must pin, so the client cannot change them.
    required_headers: dict[str, str]


def assert_kind(kind: str) -> dict[str, object]:
    if kind not in MEDIA_KINDS:
        raise ValidationError(
            {"kind": f"Unknown media kind. Choose from: {', '.join(sorted(MEDIA_KINDS))}."}
        )
    return MEDIA_KINDS[kind]


def validate_upload_request(
    *,
    tenant_id: str,
    kind: str,
    content_type: str,
    declared_bytes: int,
    owner_entity: str,
    owner_id: str,
) -> UploadPlan:
    """Validate before issuing a presigned URL.

    The returned ``object_key`` is generated here. Nothing from the client's filename
    is used, so traversal (``../``), absolute paths and overwriting another tenant's
    object are structurally impossible.
    """
    spec = assert_kind(kind)
    declared = (content_type or "").split(";")[0].strip().lower()
    if declared in FORBIDDEN_TYPES:
        raise ValidationError(
            {"content_type": "That file type is not accepted."},
            message="That file type cannot be uploaded.",
            code="forbidden_content_type",
            log_detail=f"forbidden upload type {declared!r} for kind {kind}",
        )
    permitted: frozenset[str] = spec["types"]  # type: ignore[assignment]
    if declared not in permitted:
        raise ValidationError(
            {"content_type": f"Accepted types: {', '.join(sorted(permitted))}."},
            message="That file type cannot be uploaded.",
        )
    max_bytes = int(spec["max_bytes"])  # type: ignore[arg-type]
    size = int(declared_bytes or 0)
    if size < MIN_BYTES:
        raise ValidationError({"declared_bytes": "That file looks empty."})
    if size > max_bytes:
        raise ValidationError(
            {"declared_bytes": f"Keep this under {max_bytes // (1024 * 1024)} MB."},
            message="That file is too large.",
        )
    asset_id = new_id("med")
    extension = EXTENSION_BY_TYPE[declared]
    # Tenant-first key layout so a bucket policy or prefix condition can enforce
    # isolation at the storage layer as well as in the application.
    object_key = f"tenants/{tenant_id}/{kind.lower()}/{owner_entity}/{owner_id}/{asset_id}.{extension}"
    assert_safe_object_key(object_key)
    return UploadPlan(
        asset_id=asset_id,
        kind=kind,
        object_key=object_key,
        content_type=declared,
        max_bytes=max_bytes,
        required_headers={
            "Content-Type": declared,
            # Even a mis-typed object cannot be rendered inline from the media origin.
            "Content-Disposition": "attachment",
            "x-amz-server-side-encryption": "aws:kms",
        },
    )


def sniff_content_type(payload: bytes) -> str | None:
    """Identify a payload by its magic bytes."""
    head = payload[:16]
    for content_type, signatures in IMAGE_SIGNATURES.items():
        for signature in signatures:
            if head.startswith(signature):
                if content_type == "image/webp":
                    if len(payload) >= 12 and payload[8:12] == b"WEBP":
                        return "image/webp"
                    continue
                return content_type
    return None


def validate_bytes(
    payload: bytes, *, kind: str, declared_content_type: str, expected_checksum: str | None = None
) -> dict[str, object]:
    """Inspect the uploaded content itself, after the object lands in S3.

    This is the check that matters: the browser uploaded directly to S3, so until now
    nothing has looked inside the file.
    """
    spec = assert_kind(kind)
    permitted: frozenset[str] = spec["types"]  # type: ignore[assignment]
    max_bytes = int(spec["max_bytes"])  # type: ignore[arg-type]
    size = len(payload)
    if size < MIN_BYTES:
        raise ValidationError({"file": "That file looks empty."})
    if size > max_bytes:
        raise ValidationError({"file": "That file is too large."}, message="That file is too large.")

    actual = sniff_content_type(payload)
    if actual is None:
        raise ValidationError(
            {"file": "That file type is not accepted."},
            message="We could not recognise that file type.",
            code="unrecognised_content",
        )
    if actual not in permitted:
        raise ValidationError(
            {"file": f"Accepted types: {', '.join(sorted(permitted))}."},
            message="That file type cannot be uploaded.",
        )
    declared = (declared_content_type or "").split(";")[0].strip().lower()
    if declared and declared != actual:
        # A mismatch is a strong signal of a deliberate content-type confusion attempt.
        raise ValidationError(
            {"file": "That file does not match its declared type."},
            message="That file does not match its declared type.",
            code="content_type_mismatch",
            log_detail=f"declared={declared!r} actual={actual!r} kind={kind}",
        )
    if _contains_script_markers(payload[:2048]):
        raise ValidationError(
            {"file": "That file is not accepted."},
            message="That file cannot be uploaded.",
            code="embedded_markup_rejected",
            log_detail="script or markup markers found in image header",
        )
    checksum = hashlib.sha256(payload).hexdigest()
    if expected_checksum and not _constant_equals(checksum, expected_checksum):
        raise ValidationError(
            {"checksum": "The upload was not received intact."},
            message="The upload could not be verified. Please try again.",
            code="checksum_mismatch",
        )
    return {"content_type": actual, "bytes": size, "sha256": checksum}


def _contains_script_markers(head: bytes) -> bool:
    """Catch polyglot files whose image header hides markup.

    A valid JPEG or PNG has no reason to contain ``<script`` or ``<svg`` near its
    start; a polyglot crafted to be served as HTML does.
    """
    lowered = head.lower()
    return any(marker in lowered for marker in (b"<script", b"<svg", b"<!doctype html", b"<html", b"<?php"))


def _constant_equals(left: str, right: str) -> bool:
    import hmac

    return hmac.compare_digest(str(left), str(right))


def assert_safe_object_key(key: str) -> str:
    """Reject a storage key that could escape its prefix."""
    text = str(key or "")
    if not _SAFE_KEY.match(text):
        raise ValidationError(
            {"object_key": "Invalid storage key."},
            message="That request could not be processed.",
            log_detail=f"unsafe object key {text!r}",
        )
    if ".." in text or text.startswith("/") or "//" in text:
        raise ValidationError(
            {"object_key": "Invalid storage key."},
            message="That request could not be processed.",
            log_detail=f"traversal attempt in object key {text!r}",
        )
    return text


def variant_key(object_key: str, variant: str, *, allowed: Iterable[str] = ("thumb", "card", "hero")) -> str:
    """Derive a resized-variant key from the original, keeping the same prefix."""
    if variant not in tuple(allowed):
        raise ValidationError({"variant": f"Choose one of: {', '.join(allowed)}."})
    base, _, extension = object_key.rpartition(".")
    return assert_safe_object_key(f"{base}.{variant}.{extension}")


__all__ = [
    "ALLOWED_DOCUMENT_TYPES",
    "ALLOWED_IMAGE_TYPES",
    "EXTENSION_BY_TYPE",
    "FORBIDDEN_TYPES",
    "IMAGE_SIGNATURES",
    "MAX_DOCUMENT_BYTES",
    "MAX_IMAGE_BYTES",
    "MEDIA_KINDS",
    "UploadPlan",
    "assert_kind",
    "assert_safe_object_key",
    "sniff_content_type",
    "validate_bytes",
    "validate_upload_request",
    "variant_key",
]
