# Generated by Django 5.2.17 on 2026-08-31 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('method', models.CharField(choices=[('CARD', 'Card'), ('QR_BANK_TRANSFER', 'QR / bank transfer'), ('EWALLET', 'E-wallet'), ('CASH', 'Cash'), ('STORED_VALUE', 'Stored value'), ('INVOICE', 'Invoice / offline settlement'), ('COMPLIMENTARY', 'Complimentary')], max_length=20)),
                ('display_name', models.JSONField(default=dict)),
                ('description', models.JSONField(blank=True, default=dict)),
                ('icon', models.CharField(blank=True, max_length=30)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('provider_config_ref', models.CharField(blank=True, max_length=120)),
                ('supported_currencies', models.JSONField(blank=True, default=list, help_text='Empty means every currency.')),
                ('web_enabled', models.BooleanField(default=True)),
                ('kiosk_enabled', models.BooleanField(default=False)),
                ('counter_enabled', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_types', to='tenancy.venue')),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=20)),
                ('provider', models.CharField(default='simulated', max_length=40)),
                ('provider_ref', models.CharField(blank=True, db_index=True, max_length=120)),
                ('provider_event_id', models.CharField(blank=True, max_length=120)),
                ('amount_minor', models.IntegerField()),
                ('currency', models.CharField(default='THB', max_length=3)),
                ('tendered_minor', models.IntegerField(blank=True, null=True)),
                ('change_minor', models.IntegerField(blank=True, null=True)),
                ('refunded_minor', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('VOIDED', 'Voided'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially refunded')], default='PENDING', max_length=20)),
                ('channel', models.CharField(default='ONLINE', max_length=12)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('failure_code', models.CharField(blank=True, max_length=60)),
                ('failure_message', models.CharField(blank=True, max_length=200)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='booking.booking')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymenttype',
            constraint=models.UniqueConstraint(fields=('venue', 'code'), name='uniq_payment_type_code_per_venue'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'status'], name='payments_pa_tenant__3ffcb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_payment_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id', ''), _negated=True), fields=('tenant', 'provider', 'provider_event_id'), name='uniq_provider_event'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_minor__lte', models.F('amount_minor'))), name='refund_never_exceeds_payment'),
        ),
    ]
