# Generated by Django 5.2.17 on 2026-08-31 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=40)),
                ('provider_event_id', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=40)),
                ('signature_valid', models.BooleanField(default=False)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('outcome', models.CharField(blank=True, max_length=30)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payments.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['tenant', 'provider', 'provider_event_id'], name='payments_pa_tenant__4814bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'provider', 'provider_event_id'), name='uniq_provider_event_delivery')],
            },
        ),
    ]
