# Generated by Django 5.2.17 on 2026-08-31 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('pricing', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('language', models.CharField(default='en', max_length=8)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_number', models.CharField(db_index=True, max_length=32)),
                ('channel', models.CharField(choices=[('ONLINE', 'Online'), ('KIOSK', 'Kiosk'), ('COUNTER', 'Counter'), ('PARTNER', 'Partner'), ('STAFF', 'Staff-assisted'), ('API', 'API')], default='ONLINE', max_length=12)),
                ('visit_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_PAYMENT', 'Awaiting payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('VOIDED', 'Voided'), ('RECONCILIATION', 'Held for reconciliation')], db_index=True, default='DRAFT', max_length=20)),
                ('language', models.CharField(default='en', max_length=8)),
                ('currency', models.CharField(default='THB', max_length=3)),
                ('gross_minor', models.IntegerField(default=0)),
                ('discount_minor', models.IntegerField(default=0)),
                ('service_charge_minor', models.IntegerField(default=0)),
                ('tax_minor', models.IntegerField(default=0)),
                ('rounding_adjustment_minor', models.IntegerField(default=0)),
                ('total_minor', models.IntegerField(default=0)),
                ('settlement_minor', models.IntegerField(default=0)),
                ('amount_paid_minor', models.IntegerField(default=0)),
                ('charge_snapshot', models.JSONField(blank=True, default=dict)),
                ('exchange_rate_snapshot', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('late_confirmation', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tenancy.device')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tenancy.venue')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_minor', models.IntegerField()),
                ('gross_minor', models.IntegerField()),
                ('discount_minor', models.IntegerField(default=0)),
                ('tax_minor', models.IntegerField(default=0)),
                ('net_minor', models.IntegerField(default=0)),
                ('currency', models.CharField(default='THB', max_length=3)),
                ('applied_promotions', models.JSONField(blank=True, default=list)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.booking')),
                ('price_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pricing.pricerule')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.customersegment')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='inventory.session')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.tickettype')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='item_quantity_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'email'], name='booking_cus_tenant__d57eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'status', 'visit_date'], name='booking_boo_tenant__7a9e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['venue', 'visit_date'], name='booking_boo_venue_i_c1bc14_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('tenant', 'booking_number'), name='uniq_booking_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_booking_idempotency_key'),
        ),
    ]
