# Generated by Django 5.2.17 on 2026-08-31 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cart_ref',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='PrivacyNotice',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(db_index=True, max_length=20)),
                ('language', models.CharField(default='en', max_length=8)),
                ('controller_name', models.CharField(max_length=200)),
                ('controller_contact', models.CharField(max_length=200)),
                ('dpo_contact', models.CharField(max_length=200)),
                ('body', models.JSONField(default=dict)),
                ('notice_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_hash', models.CharField(db_index=True, max_length=64)),
                ('notice_version', models.CharField(max_length=20)),
                ('language', models.CharField(default='en', max_length=8)),
                ('items', models.JSONField(default=dict)),
                ('channel', models.CharField(default='ONLINE', max_length=12)),
                ('device', models.CharField(blank=True, max_length=40)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('captured_at_utc', models.DateTimeField(db_index=True)),
                ('captured_at_local', models.CharField(blank=True, max_length=40)),
                ('is_withdrawal', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='booking.booking')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='booking.customer')),
                ('staff_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='booking.consentrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.venue')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='booking.privacynotice')),
            ],
            options={
                'ordering': ['-captured_at_utc'],
            },
        ),
        migrations.AddConstraint(
            model_name='privacynotice',
            constraint=models.UniqueConstraint(fields=('tenant', 'version', 'language'), name='uniq_notice_version_lang'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['tenant', 'contact_hash', 'captured_at_utc'], name='booking_con_tenant__3c5bb8_idx'),
        ),
    ]
