# Generated by Django 5.2.17 on 2026-08-31 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('ADMIT', 'Admit'), ('ADMIT_WITH_CHECK', 'Admit — proof required'), ('REJECT_ALREADY_USED', 'Reject — already used'), ('REJECT_WRONG_DATE', 'Reject — wrong date'), ('REJECT_WRONG_SESSION', 'Reject — wrong session'), ('REJECT_WRONG_VENUE', 'Reject — wrong venue or gate'), ('REJECT_CANCELLED', 'Reject — cancelled'), ('REJECT_REFUNDED', 'Reject — refunded'), ('REJECT_VOIDED', 'Reject — voided'), ('REJECT_BLOCKED', 'Reject — blocked'), ('REJECT_NOT_YET_VALID', 'Reject — not yet valid'), ('REJECT_EXPIRED', 'Reject — expired'), ('REJECT_UNKNOWN_CODE', 'Reject — unknown code'), ('REJECT_DEVICE', 'Reject — unregistered or deactivated device')], db_index=True, max_length=24)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('scanned_ref', models.CharField(blank=True, max_length=80)),
                ('scanned_at', models.DateTimeField(db_index=True)),
                ('scanned_at_local', models.CharField(blank=True, max_length=40)),
                ('captured_offline', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.CharField(blank=True, max_length=200)),
                ('correlation_id', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='OfflineScanConflict',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
