# Generated by Django 5.2.17 on 2026-08-31 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('booking', '0001_initial'),
        ('tenancy', '0001_initial'),
        ('ticketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinescanconflict',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_conflicts', to='ticketing.ticket'),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='access_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='tenancy.accesspoint'),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='tenancy.device'),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='override_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overrides', to='access.scanevent'),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='ticketing.ticket'),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='tenancy.venue'),
        ),
        migrations.AddField(
            model_name='offlinescanconflict',
            name='first_scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='access.scanevent'),
        ),
        migrations.AddField(
            model_name='offlinescanconflict',
            name='second_scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='access.scanevent'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['tenant', 'decision', 'scanned_at'], name='access_scan_tenant__5ec04e_idx'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['ticket', 'scanned_at'], name='access_scan_ticket__129ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['venue', 'scanned_at'], name='access_scan_venue_i_88b0e9_idx'),
        ),
    ]
