# Generated by Django 5.2.17 on 2026-08-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanevent',
            name='decision',
            field=models.CharField(choices=[('ADMIT', 'Admit'), ('ADMIT_WITH_CHECK', 'Admit — proof required'), ('REJECT_ALREADY_USED', 'Reject — already used'), ('REJECT_WRONG_DATE', 'Reject — wrong date'), ('REJECT_WRONG_SESSION', 'Reject — wrong session'), ('REJECT_WRONG_VENUE', 'Reject — wrong venue or gate'), ('REJECT_CANCELLED', 'Reject — cancelled'), ('REJECT_REFUNDED', 'Reject — refunded'), ('REJECT_VOIDED', 'Reject — voided'), ('REJECT_BLOCKED', 'Reject — blocked'), ('REJECT_NOT_YET_VALID', 'Reject — not yet valid'), ('REJECT_EXPIRED', 'Reject — expired'), ('REJECT_UNKNOWN_CODE', 'Reject — unknown code'), ('REJECT_DEVICE', 'Reject — unregistered or deactivated device')], db_index=True, max_length=30),
        ),
    ]
